app = "liveroom"
kill_signal = "SIGTERM"
kill_timeout = 5
primary_region = "cdg"
processes = []

[deploy]
# release_command = "/app/bin/migrate"
# strategy = "bluegreen"

[mounts]
source = "litefs"
destination = "/mnt/litefs"

[env]
DATABASE_PATH = "/mnt/litefs/liveroom.db"
# ECTO_IPV6 = "true"
ERL_AFLAGS = "-proto_dist inet6_tcp -kernel prevent_overlapping_partitions false"
PHX_HOST = "liveroom.app"
PORT = "8080"
# RELEASE_COOKIE set as secret
# SECRET_KEY_BASE set as secret
UMAMI_ENABLED = "true"
UMAMI_BASE_URL = "https://liveroom-umami.fly.dev"
# UMAMI_BASE_URL = "http://liveroom-umami.internal:3000" # Does not work...
# UMAMI_WEBSITE_ID set as secret
DISCORD_ENABLED = "true"
# DISCORD_WEBHOOK_URL_APP_LOGS set as secret
# DISCORD_WEBHOOK_URL_APP_NOTIFICATIONS set as secret
# GOOGLE_CLIENT_ID set as secret
# GOOGLE_CLIENT_SECRET set as secret
# ADMIN_BASIC_AUTH_USERNAME set as secret
# ADMIN_BASIC_AUTH_PASSWORD set as secret
# LITEFS_CLOUD_TOKEN set as secret
# BREVO_API_KEY set as secret

[experimental]
auto_rollback = true

[[services]]
http_checks = []
# LiteFS proxy listening port, will forward requests to app port 8080
internal_port = 8082
processes = ["app"]
protocol = "tcp"
script_checks = []
[services.concurrency]
hard_limit = 1000
soft_limit = 1000
type = "connections"

[[services.ports]]
force_https = true
handlers = ["http"]
port = 80

[[services.ports]]
handlers = ["tls", "http"]
port = 443

[[services.tcp_checks]]
grace_period = "1s"
interval = "15s"
restart_limit = 0
timeout = "2s"
